require('plugins.cmp')
require('plugins.devicons')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.nvim-colorizer')
require('plugins.which-key')
require('plugins.tabout')
require('plugins.indent-blankline')
require('plugins.close-buffers')
require('plugins.gitsigns')
require('plugins.neoscroll')
-- require('plugins.neorg')
require('plugins.focus')
require('plugins.specs')
require('plugins.nvim-autopair')
require('plugins.nvim-gps')
require('plugins.nvim-tree')
require('plugins.sniprun')
